CREATE SCHEMA plum;

CREATE TABLE plum.users (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())
WITH (OIDS = FALSE);

CREATE TABLE plum.libraries (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(128) NOT NULL,
    description VARCHAR(512) NOT NULL,
    created_by INTEGER NOT NULL REFERENCES plum.users ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())
WITH (OIDS = FALSE);

CREATE TABLE plum.memberships (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES plum.users ON DELETE RESTRICT,
    library_id INTEGER NOT NULL REFERENCES plum.libraries ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	deleted_at TIMESTAMPTZ,
    UNIQUE (user_id, library_id))
WITH (OIDS = FALSE);

CREATE TABLE plum.video_urls (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    url VARCHAR(512) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())
WITH (OIDS = FALSE);

CREATE TABLE plum.videos (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(128) NOT NULL,
    description VARCHAR(512) NOT NULL,
    video_url_id INTEGER NOT NULL REFERENCES plum.video_urls ON DELETE RESTRICT,
    library_id INTEGER NOT NULL REFERENCES plum.libraries ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())
WITH (OIDS = FALSE);

CREATE TABLE plum.annotations (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    comment VARCHAR(128) NOT NULL,
    video_id INTEGER NOT NULL REFERENCES plum.videos ON DELETE RESTRICT,
    user_id INTEGER NOT NULL REFERENCES plum.users ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())
WITH (OIDS = FALSE);