CREATE TABLE plum.roles (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	title TEXT NOT NULL,
	library_id INTEGER NOT NULL REFERENCES plum.libraries ON DELETE RESTRICT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	deleted_at TIMESTAMPTZ)
WITH (OIDS = FALSE);

ALTER TABLE plum.memberships ADD COLUMN
	role_id INTEGER NOT NULL REFERENCES plum.roles ON DELETE RESTRICT;

CREATE TABLE plum.role_privileges (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	role_id INTEGER NOT NULL REFERENCES plum.roles ON DELETE RESTRICT,
	privilege_alias VARCHAR(32) NOT NULL,
	UNIQUE (role_id, privilege_alias))
WITH (OIDS = FALSE);