CREATE TABLE plum.replies (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES plum.users ON DELETE RESTRICT,
    annotation_id INTEGER NOT NULL REFERENCES plum.annotations ON DELETE RESTRICT,
    text VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modified_at TIMESTAMPTZ NULL,
    deleted_at TIMESTAMPTZ NULL)
WITH (OIDS = FALSE);