CREATE TABLE plum.invitations (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    url_key VARCHAR(7) NOT NULL UNIQUE,
	role_id INTEGER NOT NULL REFERENCES plum.roles ON DELETE RESTRICT,
    membership_id INTEGER NOT NULL REFERENCES plum.memberships ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	deleted_at TIMESTAMPTZ,
	expires_at TIMESTAMPTZ)
WITH (OIDS = FALSE);